"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n7a&wc5h(9_68zxeyse0rd!(+*f)cdt5!ew*mu3&(if9*r*4tw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '', '']


# Application definition

INSTALLED_APPS = [
    'personal',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }, 
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'app.log',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false']
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'personal': {
            'handlers': ['file', 'mail_admins'],
            'level': 'DEBUG'
        },
    },
}

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    
'default': {
         #'ENGINE': 'django.db.backends.mysql',
         #'NAME': 'crdb',
         #'USER': 'root',
         #'PASSWORD': '',
         #'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
         #'PORT': '3306',

       

        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/' if DEBUG else '/crsystem/static/'
LOGIN_URL = '/login/' if DEBUG else '/crsystem/login/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
ADMINS = (
          ('wfsiew', 'wingfei.siew@redtone.com'),
          ('ainur', 'ainur.fadzil@redtone.com'),
          )
ADMIN_CCMAIL = (
          ('ainur', 'ainur.fadzil@redtone.com'),
          )
SERVER_EMAIL = 'REDtone CRSystem<redtonernd@biz.redtone.com>'
EMAIL_HOST = 'mail.redtone.com'
EMAIL_PORT = 587
EMAIL_SUBJECT_PREFIX = '[crsystem] '

AUTHENTICATION_BACKENDS = ('personal.backends.ClientAuthBackend',)
AUTH_USER_MODEL = 'personal.User'

SESSION_COOKIE_NAME = 'crsystem'
SESSION_COOKIE_PATH = '/' if DEBUG else '/crsystem'

CSRF_COOKIE_NAME = 'csrftoken_crsystem'
CSRF_COOKIE_PATH = '/' if DEBUG else '/crsystem'

TMP_UPLOAD_PATH = os.path.join(BASE_DIR, 'tmp')
UPLOAD_PATH = os.path.join(BASE_DIR, 'uploads') if DEBUG else r'E:\apps\crsystem_uploads'

CLIENT_ID = '977639017537-oug0ptufdcv77g27iubartpbj191484b.apps.googleusercontent.com'
CLIENT_SECRET = '0Z8vwMDo3cPdXPJUClRK0vv6'
REDIRECT_URI = 'http://localhost:8000/auth/callback/' if DEBUG else 'https://apps.redtone.com:8585/crsystem/auth/callback/'

EDIT_URI = 'http://localhost:8000/edit/' if DEBUG else 'https://apps.redtone.com:8585/crsystem/edit/'
