# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
    ]
