# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user_email',
            field=models.CharField(default=datetime.datetime(2016, 7, 14, 17, 24, 23, 700000), max_length=100),
            preserve_default=False,
        ),
    ]
