# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_app_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appsid', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reqform',
            name='description1',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='reqform',
            name='description2',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
